import {
  PhoneOutlined,
  LockOutlined,
  MenuUnfoldOutlined,
  MenuFoldOutlined,
  ShopOutlined,
  LogoutOutlined,
  UserOutlined,
  CustomerServiceOutlined,
  MessageOutlined,
  CarOutlined,
  EditOutlined,
  SearchOutlined,
  DeleteFilled,
  DeleteOutlined,
  PlusSquareOutlined,
} from '@ant-design/icons';

export default {
  PhoneOutlined,
  LockOutlined,
  MenuUnfoldOutlined,
  MenuFoldOutlined,
  ShopOutlined,
  LogoutOutlined,
  UserOutlined,
  CustomerServiceOutlined,
  MessageOutlined,
  CarOutlined,
  EditOutlined,
  SearchOutlined,
  DeleteFilled,
  DeleteOutlined,
  PlusSquareOutlined,
};
